# Generated by Django 5.1.3 on 2024-12-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_image',
            field=models.CharField(default='accounts/profiles/pic7.jpg', max_length=255),
        ),
    ]
