# Generated by Django 5.1.3 on 2024-12-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_account_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_image',
            field=models.CharField(blank=True, default='accounts/profiles/pic6.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_phone',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
