# Generated by Django 5.1.3 on 2024-12-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_account_user_image_alter_account_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_image',
            field=models.CharField(blank=True, default='accounts/profiles/pic4.jpg', max_length=255, null=True),
        ),
    ]
