# Generated by Django 5.1.3 on 2024-12-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_account_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_phone',
        ),
        migrations.AlterField(
            model_name='account',
            name='user_image',
            field=models.CharField(default='accounts/profiles/pic3.jpg', max_length=255),
        ),
    ]
