# Generated by Django 5.1.3 on 2024-12-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_account_user_phone_alter_account_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_image',
            field=models.CharField(default='accounts/profiles/pic9.jpg', max_length=255),
        ),
    ]
