# Generated by Django 5.1.3 on 2024-12-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_alter_account_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_image',
            field=models.CharField(blank=True, default='accounts/profiles/pic8.jpg', max_length=255),
        ),
    ]
