# Generated by Django 5.1.3 on 2024-12-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_useranswer_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('quiz', models.CharField(blank=True, max_length=40, null=True)),
                ('score', models.CharField(blank=True, max_length=3, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
